### ISSUE TITLE
Das ist noch zu tun derzeit

### ISSUE THREAD

**Issue by Cyperghost** [Cyperghost/routecms#1]
Noch zu tun ist derzeit

- [ ] Bearbeitung des Template System für Include Dateien
- [ ] Hinzufügen für Events im Template System
- [ ] Bearbeitung der Gruppen fertig stellen
- [ ] Bearbeitung der Benutzer im Admin-Panel erstellen
- [ ] Das Sprachsystem von Json in die Datenbank eintragen
- [ ] Avatar verwaltung hinzufügen
- [ ] Dateianhangs System erstellen
- [ ] Plugin System erstellen
- [ ] Template System mit verschiedenen Deign verknüpfen
- [ ] Eigene Seiten im Admin-Panel erstellen
- [ ] Suchmaschinenoptimierung für die Startseite

**Comment by mrpixeldream** [comment]
Du solltest diese Punkte in eigene Issues aufteilen und jeweils genauer beschreiben, damit auch andere wissen, was du meinst.

**Comment by Cyperghost** [comment]
Ja kann ich gerne machen :)
