### ISSUE TITLE
User Password Hashing

### ISSUE THREAD

**Issue by ddmler** [Cyperghost/routecms#12]
Sha1 mit Salt ist nicht sicher genug.
"SHA-1's use on the Internet has been deprecated since 2011" - Chromium Blog

Besser die Password_Hash API benutzen (bcrypt ist der Standard): http://php.net/manual/en/book.password.php
Dann muss sich auch nicht um das salten gekümmert werden.
Das Manual zeigt auch eine Funktion um einen guten cost Parameter zu finden, die sollte eventuell ins CMS implementiert werden.

**Comment by Cyperghost** [comment]
SHA1 mit einer zufälligen Zeichenkette ist doch genau so sicher? Der Salat steht nur in der Datenbank und wird niemals an den User gesendet somit kann das Passwort überhaupt nicht erraten werden.

**Comment by ddmler** [comment]
http://codahale.com/how-to-safely-store-a-password/
Es könnte ja auch jemand Unbefugtes Zugriff auf die Datenbank bekommen und hat dann alle Passwörter als SHA1, was er dann relativ leicht knacken kann.

**Comment by Cyperghost** [comment]
Wenn er zugriff auf die Datenbank hat ist es denke ich mal das kleinste Problem das er die Passwörter in SHA1 sehen kann.

**Comment by ddmler** [comment]
Es macht trotzdem keinen Sinn bewusst einen schwächeren Hash Algorithmus zu benutzen, wenn eine viel bessere Alternative nicht schwer zu implementieren ist. (sogar mit weniger Code)

**Comment by Cyperghost** [comment]
Kann ja jemand anders jederzeit einfügen. Im Moment kann ich es leider nicht machen ich habe noch zu viel mit anderen Sachen zu tun.

**Comment by Cyperghost** [comment]
Wird kommen aber jetzt noch nicht.

**Comment by Cyperghost** [comment]
P.s.
Falschen Button gedrückt :D
