### ISSUE TITLE
Klassen Abhängigkeiten abbauen

### ISSUE THREAD

**Issue by ddmler** [Cyperghost/routecms#13]
Stichwort Class Decoupling

Beispiel: Routecms Klasse instantiiert im Konstruktor andere Klassen (Database, Languages)
oder auch im Konstruktor: Zugriffe auf statische Objekte (EventManger::loadEvents();)

Nicht nur diese Beispielklasse, sondern das ganze CMS braucht hier hingehend eine kleine Überarbeitung mit weniger static und anstatt Klassen im Konstruktor zu instantiieren lieber Dependency Injection benutzen.

Falls nicht ersichtlich ist, wieso der Gebrauch von zu viel static und dem Instantiieren von Klassen innerhalb anderer Klassen bad practice ist: http://fabien.potencier.org/media/talk/2008/decouple-your-code-for-reusability-ipc-2008.pdf

(kleine Anmerkung: Ich würde die Klasse "Languages" umbenennen in "Language", Einzahl ist sonst auch überall benutzt worden)

**Comment by Cyperghost** [comment]
Das ist derzeit in Arbeit. Wird jedoch noch etwas dauern
