### ISSUE TITLE
DB escapeString Funktion unsicher

### ISSUE THREAD

**Issue by ddmler** [Cyperghost/routecms#14]
Es ist nicht empfohlen addslashes zu benutzen, um etwas für die Datenbank zu maskieren. (es gibt sql injections die hierdurch nicht maskiert werden) Am besten wäre es für alle Querys prepared Statements mit Parametern zu benutzen, ansonsten PDO quote. (bei prepared statements kann man sich sicher sein das quote nicht vergessen zu haben)

Außerdem sollte das PDO Attribut hinzugefügt werden: 
$this->pdo->setAttribute(\PDO::ATTR_EMULATE_PREPARES, false); 
(um client side prepared statements zu unterbinden)

Am Ende muss unter der Routecms Klasse noch dieses komische Konstrukt entfernt werden, welche die Funktion in eine andere Funktion packt (warum sollte man das machen?)

**Comment by Cyperghost** [comment]
Das kommt in der neuen Version rein ist schon fertig. Muss ich nur noch wenn Zeit ist hochladen
