### ISSUE TITLE
Singleton/static Konstrukte ersetzen

### ISSUE THREAD

**Issue by ddmler** [Cyperghost/routecms#15]
public static function getDB() {
	return self::$db;
}
in Verbindung mit Sachen wie
Routecms::getDB()->escapeString($string);

ergeben eine Art Singleton. Wie will man so ordentliche Unit Tests durchführen, einen Mock erstellen oder den Code wiederverwenden? ;)
Besser: Die Datenbank instantiieren und das eine Objekt dann in die Klassen die es benötigen injizieren (DI)

**Comment by Cyperghost** [comment]
Dabei bin ich derzeit am arbeiten und beim nächsten Upload eingefügt

**Comment by ddmler** [comment]
Wie ich es eigentlich gemeint hatte:
Kein Singleton und kein Static benutzen.
Beispiel User Klasse:
Jetzt:
- extends DBObject
- $statement = Routecms::getInstance()->getDB()->statement($sql);

Danach:
- __construct(DatabaseInterface $db){ // Database implements DatabaseInterface
$this->db = $db;
}
- $statement = $this->db->statement($sql);

Routecms::getDB() und sowas fällt dann weg, was bringts: Willst du mal Unit Tests oder so machen (wäre ja nicht schlecht für ein CMS) kannst du ganz einfach einen Mock in die Klasse injecten und schon wird nichts wirklich in die Datenbank gespeichert. (Beim aktuellen Design nicht möglich, da Routecms::getDB() IMMER die echte Datenbank Klasse aufruft und alles auch wirklich abspeichert bzw. ändert in der Datenbank.) Außerdem ist die Klasse User so nicht mehr von der Klasse RouteCMS abhängig. 
Wenn du nur eine Routecms Klasse brauchst (gilt für alle Singletons jetzt), dann benutz doch eine Factory zum Erstellen der Objekte? Dann wird nur 1 mal der new Operator benutzt für diese Klasse ohne die ganze Klasse dabei global verfügbar zu machen (mittels static oder Singleton)
Bzw. die Routecms Klasse wird dann die Factory die die wichtigsten Komponenten lädt (Database, Language und so) ABER nicht als statisch (global) zur Verfügung stellt sondern die eine erstellte Instanz von DB z.b. per Konstruktor DI an User oder welche Klasse es halt braucht übergibt.

Ziel ist es ja eine gewisse Modularisierung zu erreichen. Im Moment ist das ja ein wenig wie funktionale Programmierung (alles ist von überall zu erreichen, ich kann einfach überall Routecms::irgendwas machen und das ist nur eine schönere Schreibweise als function irgendwas())

**Comment by Cyperghost** [comment]
Es war aber mein Idee und auf meine absicht das man von überall die Funktionen aus der Routecms Klasse aufrufen kann. 

Am besten wäre es wenn du ein Request machen könnest wie du meinst es aussehen sollte, dann überlege ich es mir.
